#!/bin/zsh

# Get v4 and v6 addresses
v4=$(dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com)
v4=${v4//\"/}

echo $v4


# Remove quotes
v6=$(dig -6 TXT +short o-o.myaddr.l.google.com @ns1.google.com)
v6=${v6//\"/}

# Check if they are the same
if [ "$v4" != "$v6" ]; then
  echo $v4
  echo $v6
fi
